[workspace]

members = [
  "algorithms",
  "concurrent",
  "concurrent_algorithms",
  "csv_reader",
  "datatypes",
  "libs",
  "local_nodes",
  "serial",
  "serial_algorithms",
]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
overflow-checks = true
